# ================================================================
# cicd-pipelines/.gitlab-ci-stag.yml 
# this pipeline is for staging environment for deployment testing
# ================================================================

# Define variables at the top so BOTH jobs can use them
variables:
  ENVIRONMENT: "staging"
  IMAGE_TAG: "latest"
  STAGING_PROJECT_ID: "gcp_stag_project_id"
  STAGING_PROJECT_REGION: "us-central1"
  AR_REPOSITORY: "spinotale-insight-generation-${ENVIRONMENT}"
  IMAGE_AR_PATH: "${STAGING_PROJECT_REGION}-docker.pkg.dev/${STAGING_PROJECT_ID}/${AR_REPOSITORY}/spinotale-insight-generation:${IMAGE_TAG}"
  GCP_CLOUD_RUN_SERVICE_NAME: "spinotale-insight-generation"

build-and-push-image:
  stage: build
  image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - apt-get update && apt-get install -y docker.io
    - gcloud auth activate-service-account --key-file="$CENTRAL_SA_KEY"
    - gcloud config set project "${STAGING_PROJECT_ID}"
    - gcloud auth configure-docker "${STAGING_PROJECT_REGION}-docker.pkg.dev" --quiet
  script:
    - TIMESTAMP=$(date +%Y/%m/%d-%H:%M:%S)
    - echo "Build process started at ${TIMESTAMP}..."
    - docker build -t "${IMAGE_AR_PATH}" .
    - docker push "${IMAGE_AR_PATH}"
    - echo "Build process completed at ${TIMESTAMP}..."

  retry: 1
  interruptible: false
  when: manual
  only:
    - staging

deploy-to-cloud_run:
  stage: deploy
  needs: ["build-and-push-image"]
  image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
  when: manual
  before_script:
    - gcloud auth activate-service-account --key-file="$CENTRAL_SA_KEY"
    - gcloud config set project "${STAGING_PROJECT_ID}"
  script:
    - TIMESTAMP=$(date +%Y/%m/%d-%H:%M:%S)
    - echo "Deploy process started at ${TIMESTAMP}..."
    - gcloud run deploy $GCP_CLOUD_RUN_SERVICE_NAME 
      --image=$IMAGE_AR_PATH 
      --platform=managed 
      --region=$STAGING_PROJECT_REGION
    - echo "Deployed image to Cloud Run."

  retry: 1
  interruptible: false
  when: manual
  only:
    - staging